fragment SectionCollectionMain on SectionCollectionMain {
  id
  __typename
  modulePromoBanner {
    adminTitle
    desktopImage {
      altText
      height
      url
      width
    }
    mobileImage {
      altText
      height
      url
      width
    }
    urlLink
  }
}
