fragment SectionFullWidthVideo on SectionFullWidthVideo {
  id
  adminTitle
  videoTitle
  salonsVideoDescription: description
  desktopLogoHeader {
    altText
    height
    width
    url
  }
  mobileLogoHeader {
    altText
    height
    width
    url
  }
  tabletLogoHeader {
    altText
    height
    width
    url
  }
  videoFile {
    url
    height
    width
  }
  thumbnail {
    altText
    height
    width
    url
  }
}
