import { AccountSidebarProps } from './AccountSidebar.types'

export const mock: AccountSidebarProps = {
  menu: {
    id: 'gid://shopify/Menu/225871135033',
    items: [
      {
        id: 'gid://shopify/MenuItem/528646996281',
        resourceId: null,
        tags: Array(0),
        title: 'Dashboard',
        type: 'HTTP',
        url: 'https://hairhouse-au.myshopify.com/account',
        to: '/account',
        items: Array(0),
      },
      {
        id: 'gid://shopify/MenuItem/528647029049',
        resourceId: null,
        tags: Array(0),
        title: 'Wishlists',
        type: 'HTTP',
        url: 'https://hairhouse-au.myshopify.com/account/wishlists',
        to: '/wishlists',
        items: Array(0),
      },
      {
        id: 'gid://shopify/MenuItem/528647061817',
        resourceId: null,
        tags: Array(0),
        title: 'Style Status',
        type: 'HTTP',
        url: 'https://hairhouse-au.myshopify.com/account/style-status',
        to: '/style-status',
        items: Array(0),
      },
      {
        id: 'gid://shopify/MenuItem/528647094585',
        resourceId: null,
        tags: Array(0),
        title: 'Orders',
        type: 'HTTP',
        url: 'https://hairhouse-au.myshopify.com/account/orders',
        to: '/orders',
        items: Array(0),
      },
      {
        id: 'gid://shopify/MenuItem/528647127353',
        resourceId: null,
        tags: Array(0),
        title: 'Preferences',
        type: 'HTTP',
        url: 'https://hairhouse-au.myshopify.com/account/preferences',
        to: '/preferences',
        items: [
          {
            id: 'gid://shopify/MenuItem/528647160121',
            resourceId: null,
            tags: Array(0),
            title: 'Customer Profile',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com/account/customer-profile',
            to: '/customer-profile',
            items: [],
          },
          {
            id: 'gid://shopify/MenuItem/528647192889',
            resourceId: null,
            tags: Array(0),
            title: 'Password',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com/account/password',
            to: '/password',
            items: [],
          },
          {
            id: 'gid://shopify/MenuItem/528647225657',
            resourceId: null,
            tags: Array(0),
            title: 'Hair Profile',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com/account/hair-profile',
            to: '/hair-profile',
            items: [],
          },
          {
            id: 'gid://shopify/MenuItem/528647258425',
            resourceId: null,
            tags: Array(0),
            title: 'Communication',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com/account/communication',
            to: '/communication',
            items: [],
          },
        ],
      },
      {
        id: 'gid://shopify/MenuItem/528647291193',
        resourceId: null,
        tags: Array(0),
        title: 'Sign out',
        type: 'HTTP',
        url: 'https://hairhouse-au.myshopify.com/account/logout',
        to: '/logout',
        items: Array(0),
      },
    ],
    handle: 'Menu',
    itemsCount: 4,
    title: 'Menu',
  },
}
