fragment SocialMediaCtaLarge on SocialMediaCtaLarge {
  id
  adminTitle
  handle
  ctaText
  platformLinks {
    ... on LinkIcon {
      linkUrl
      openInNewWindow
      iconFile {
        url
        fileName
      }
    }
  }
  imageGrid {
    ... on Asset {
      url
      fileName
      altText
    }
  }
  fullWidthTemplates {
    url
  }
}
