#import "../app/sections/header/Header.fragment.gql"
#import "../app/sections/footer/Footer.fragment.gql"
#import "../../app/sections/sectionCollectionMain/SectionCollectionMain.fragment.gql"
#import "../../app/sections/sectionPreezieProductFinder
#import "../app/sections/twoColumnText/TwoColumnText.fragment.gql"
#import "../app/sections/imageWithCard/ImageWithCard.fragment.gql"
#import "../app/sections/multiColumnContent/MultiColumnContent.fragment.gql"
#import "../app/sections/footer/Footer.fragment.gql"
#import "../app/sections/header/Header.fragment.gql"
#import "../app/sections/FeatureProductCarouselTabbed.fragment.gql"
#import "../app/sections/textAndImageBlockSection/TextAndImageBlockSection.fragment.gql"

query collectionPages($handle: String) {
  collectionPages(where: { handle: $handle }, first: 1) {
    id
    hideBreadcrumb
    heroBannerHeading
    heroBannerDescription {
      html
    }
    desktopImage {
      altText
      height
      mimeType
      url
      width
    }
    mobileImage {
      altText
      height
      mimeType
      url
      width
    }
    shopifyId
    collection {
      id
      handle
      title
    }
    seoText1 {
      html
      text
    }
    seoText2 {
      html
      text
    }
    sections {
      ... on Node {
        id
        __typename
      }
      ... on SectionCollectionMain {
        ...SectionCollectionMain
      }
      ... on SectionPreezieProductFinder {
        ...SectionPreezieProductFinder
      }
      ... on SectionBlogCarousel {
        ...SectionBlogCarousel
      }
      ... on BrandLogoGrid {
        ...BrandLogoGrid
      }
      ... on SectionCategoryCarousel {
        ...SectionCategoryCarousel
      }
      ... on SectionCollectionSubcategoryLink {
        ...SectionCollectionSubcategoryLink
      }
      ... on SectionCollectionDropDown {
        ...SectionCollectionDropDown
      }
      ... on SectionSeoText {
        ...TwoColumnText
      }
      ... on SectionFullWidthImageAndCopy {
        ...SectionFullWidthImageAndCopy
      }
      ... on SectionVideoCarousel {
        ...SectionVideoCarousel
      }
      ... on EditorialTile {
        ...EditorialTile
      }
      ... on FeatureProductCarouselTabbed {
        ...FeatureProductCarouselTabbed
      }
      ... on SectionImageAndTextGrid {
        ...TextAndImageBlockSection
      }
    }
  }
  websiteConfigs(first: 1) {
    footer {
      ...Footer
    }
    header {
      ...Header
    }
  }
}
