fragment ProductBenefitsGrid on ProductBenefitsGrid {
  id
  items {
    ... on ProductBenefitsItem {
      id
      image {
        altText
        url
        width
        height
        id
      }
    }
  }
}
