fragment BuyingGuidesFeaturedProductsElements on FeaturedProducts {
  id
  title
  subtitle
  rating
  totalRating
  products: getCollectionByHandle {
    id
    handle
    collection {
      id
      title
      publishedAt
      handle
      vendor
      variants(first: 1) {
        nodes {
          id
          image {
            url
            altText
            width
            height
          }
          price {
            amount
            currencyCode
          }
          compareAtPrice {
            amount
            currencyCode
          }
          selectedOptions {
            name
            value
          }
          product {
            handle
            title
          }
        }
      }
      description(truncateAt: 100)
    }
  }
}
