fragment CareersCTAFragment on SectionContentLinkBlock {
  adminTitle
  contentBlock {
    adminTitle
    headingText
    backgroundColour {
      hex
    }
    icon {
      altText
      url
      width
      height
    }
    linkText
    linkUrl
  }
}
