fragment FullWidthImage on FullWidthImage {
  adminTitle
  imageDesktop {
    altText
    image {
      height
      url
      width
    }
  }
  imageMobile {
    altText
    image {
      height
      url
      width
    }
  }
}
