export const shopifyLayoutMock = {
  menu: {
    id: 'gid://shopify/Menu/216217026873',
    items: [
      {
        id: 'gid://shopify/MenuItem/504809324857',
        resourceId: null,
        tags: [],
        title: 'SHOP',
        type: 'CATALOG',
        url: 'https://hairhouse-au.myshopify.com/collections/all',
        items: [
          {
            id: 'gid://shopify/MenuItem/518700138809',
            resourceId: null,
            tags: [],
            title: 'New',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/518700171577',
            resourceId: null,
            tags: [],
            title: 'Brands',
            type: 'COLLECTIONS',
            url: 'https://hairhouse-au.myshopify.com/collections',
            isExternal: false,
            target: '_self',
            to: '/collections',
          },
          {
            id: 'gid://shopify/MenuItem/518700204345',
            resourceId: null,
            tags: [],
            title: 'Hair',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/518700237113',
            resourceId: null,
            tags: [],
            title: 'Electrical',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519017922873',
            resourceId: null,
            tags: [],
            title: 'Mens',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519017955641',
            resourceId: null,
            tags: [],
            title: 'Beauty',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519017988409',
            resourceId: null,
            tags: [],
            title: 'Gifts',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018021177',
            resourceId: null,
            tags: [],
            title: 'Offers',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018053945',
            resourceId: null,
            tags: [],
            title: 'Clearance',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
        ],
        isExternal: false,
        target: '_self',
        to: '/products',
      },
      {
        id: 'gid://shopify/MenuItem/519018086713',
        resourceId: null,
        tags: [],
        title: 'ABOUT US',
        type: 'HTTP',
        url: 'https://hairhouse-au.myshopify.com#',
        items: [
          {
            id: 'gid://shopify/MenuItem/519018119481',
            resourceId: null,
            tags: [],
            title: 'Store Locator',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018152249',
            resourceId: null,
            tags: [],
            title: 'Hair Appointment',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018185017',
            resourceId: null,
            tags: [],
            title: 'Piercing Appointment',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018217785',
            resourceId: null,
            tags: [],
            title: 'The Cut',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018250553',
            resourceId: null,
            tags: [],
            title: 'Style Society',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018283321',
            resourceId: null,
            tags: [],
            title: 'Gift Vouchers',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018316089',
            resourceId: null,
            tags: [],
            title: 'Own a Hairhouse',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018348857',
            resourceId: null,
            tags: [],
            title: 'Careers',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
        ],
        isExternal: false,
        target: '_self',
        to: '/',
      },
      {
        id: 'gid://shopify/MenuItem/519018381625',
        resourceId: null,
        tags: [],
        title: 'QUICK HELP',
        type: 'HTTP',
        url: 'https://hairhouse-au.myshopify.com#',
        items: [
          {
            id: 'gid://shopify/MenuItem/519018414393',
            resourceId: null,
            tags: [],
            title: 'Book Appointment',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018447161',
            resourceId: null,
            tags: [],
            title: 'My Account',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018479929',
            resourceId: null,
            tags: [],
            title: 'Help Centre',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018512697',
            resourceId: null,
            tags: [],
            title: 'Shipping',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018545465',
            resourceId: null,
            tags: [],
            title: 'Returns',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018578233',
            resourceId: null,
            tags: [],
            title: 'Payment Methods',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018611001',
            resourceId: null,
            tags: [],
            title: 'Click & Collect',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
          {
            id: 'gid://shopify/MenuItem/519018643769',
            resourceId: null,
            tags: [],
            title: 'Rendr',
            type: 'HTTP',
            url: 'https://hairhouse-au.myshopify.com#',
            isExternal: false,
            target: '_self',
            to: '/',
          },
        ],
        isExternal: false,
        target: '_self',
        to: '/',
      },
    ],
  },
  menuBottom: {
    id: 'gid://shopify/Menu/221866000697',
    items: [
      {
        id: 'gid://shopify/MenuItem/518697222457',
        resourceId: null,
        tags: [],
        title: 'Terms & Conditions',
        type: 'HTTP',
        url: 'https://hairhouse-au.myshopify.com#',
        items: [],
        isExternal: false,
        target: '_self',
        to: '/',
      },
      {
        id: 'gid://shopify/MenuItem/518697255225',
        resourceId: null,
        tags: [],
        title: 'Whistle Blower',
        type: 'HTTP',
        url: 'https://hairhouse-au.myshopify.com#',
        items: [],
        isExternal: false,
        target: '_self',
        to: '/',
      },
      {
        id: 'gid://shopify/MenuItem/518697287993',
        resourceId: null,
        tags: [],
        title: 'Privacy Policy',
        type: 'HTTP',
        url: 'https://hairhouse-au.myshopify.com#',
        items: [],
        isExternal: false,
        target: '_self',
        to: '/',
      },
    ],
  },
}

export const legalLinks = [
  {
    id: '1',
    linkText: 'Terms & Conditions',
    openInNewWindow: false,
    url: '',
  },
  {
    id: '2',
    linkText: 'Whistle Blower',
    openInNewWindow: false,
    url: '',
  },
  {
    id: '3',
    linkText: 'Privacy Policy',
    openInNewWindow: false,
    url: '',
  },
]
