fragment SectionCategoryCarousel on SectionCategoryCarousel {
  backgroundColour {
    hex
  }
  title
  tilesAlignment
  categories {
    heading
    url
    image {
      altText
      id
      url
    }
  }
}
